### ISSUE TITLE
Automate Tarball Generation with GitHub Actions Webhook Integration

### ISSUE THREAD

**Issue by harvenstar** [harvenstar/sagemaker-code-editor#1]
# Current Situation Analysis

## What is a Webhook in this Context?

A **webhook** is an automated HTTP callback that triggers when specific events occur. In GitHub:

- **GitHub Webhook**: Automatically triggers when you create a release/tag
- **Purpose**: Starts the build process without manual intervention
- **Event**: `release.published` or `push.tags` events

### Current (Manual Process):
1. ✅  Manually created release "Tarball generation POC v0.1.0-rc1" 
2. ✅ Manually uploaded `code-editorv0.1.0-rc1.tar.gz` (19.8 MB)
3. ❌ This requires manual work each time

### Target (Automated Process):
1. 🎯 Push a tag (e.g., `v0.2.0`)
2. 🎯 GitHub webhook automatically triggers
3. 🎯 GitHub Actions builds tarball
4. 🎯 Automatically uploads to release
5. 🎯 Optionally uploads to S3 bucket

### 1. GitHub Actions Workflow (Webhook Receiver)
```yaml
name: Automated Tarball Build and Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0, v0.2.0-rc1
  release:
    types: [published]  # Alternative webhook trigger

jobs:
  build-tarball:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          
      - name: Setup build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y quilt nodejs npm
          
      - name: Apply patches and build
        run: |
          ./scripts/install.sh -t ${{ github.ref_name }}
          
      - name: Upload to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./sagemaker-code-editor-${{ github.ref_name }}.tar.gz
          asset_name: sagemaker-code-editor-${{ github.ref_name }}.tar.gz
          asset_content_type: application/gzip
          
      - name: Upload to S3 (Optional)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp ./sagemaker-code-editor-${{ github.ref_name }}.tar.gz \
            s3://your-bucket/releases/sagemaker-code-editor-${{ github.ref_name }}.tar.gz
```

### 2. Webhook Flow Diagram
```
Tag Push (v0.2.0) → GitHub Webhook → GitHub Actions → Build Tarball → Upload Assets
     ↓                    ↓              ↓              ↓              ↓
 Developer        Automatic        Runs on         Executes        GitHub Release
 creates tag      trigger          Ubuntu VM       install.sh      + S3 (optional)
```

## Code-Server Comparison

Looking at [code-server's approach](https://github.com/coder/code-server):
- They use GitHub Actions for automated releases
- Trigger on tag creation (`v*` pattern)
- Build multiple artifacts (binaries, tarballs, packages)
- Upload to GitHub releases automatically
- Use semantic versioning for releases

## Next Steps

1. **Create GitHub Actions workflow file** (`.github/workflows/release.yml`)
2. **Test with a development tag** (e.g., `v0.2.0-test`)
3. **Validate automation works** before production use
4. **Add S3 integration** if required by the team
5. **Update release documentation** for the new process

## Benefits of Automation

- ✅ **Consistency**: Same build environment every time
- ✅ **Speed**: No manual upload steps
- ✅ **Reliability**: Reduces human error
- ✅ **Scalability**: Can handle multiple releases easily
- ✅ **Audit Trail**: All builds are logged and traceable

## Current Task Clarification

The current task will evolve from:
- ❌ "Manual tarball creation and upload"
- ✅ **"Implement GitHub Actions automation for tarball generation and release"**
