### ISSUE TITLE
Details

### ISSUE THREAD

**Issue by harvenstar** [harvenstar/sagemaker-code-editor#10]
1. Native CodeBuild–GitHub integration
   - Create an AWS CodeStar connection (AWS Developer Tools → Connections) and connect it to your GitHub repo
   - Edit your CodeBuild project source and switch the provider to “GitHub (via CodeStar)” using that connection
   - Under the project’s **Webhook** settings, enable `pull_request` events
   - On every new commit or PR update, CodeBuild will trigger and post check-runs back to GitHub automatically

2. GitHub Actions middleware
   - Add a workflow file under `.github/workflows/` that runs on `pull_request` events
   - Use the [`aws-actions/aws-codebuild-run-build`](https://github.com/aws-actions/aws-codebuild-run-build) action to kick off builds
   - Set `wait-for-completion: true` so the Action job reflects success/failure as a check-run in GitHub

Example `.github/workflows/codebuild-pr.yml`:

```yaml
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  codebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger AWS CodeBuild project
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: my-codebuild-project-name
          wait-for-completion: true
        env:
          AWS_REGION: us-west-2
```

After merging this: every PR will show a “codebuild” check.
